export type Question={prompt:string;options:string[];answer:number};
export type Phase={id:number;title:string;duration:string;goal:string;topics:string[];projects:string[];questions:Question[]};

const q=(prompt:string,options:string[],answer:number):Question=>({prompt,options,answer});
export const phases:Phase[]=[
 {id:1,title:"Computer Science Fundamentals",duration:"6 weeks",goal:"Understand why software works.",topics:["Data structures","Algorithms","Complexity analysis","Operating systems","Networks"],projects:["Custom HashMap","File Explorer Tree","Social Network Graph","Route Optimization","Sorting Benchmark"],questions:[q("Which structure gives average O(1) key lookup?",["Linked list","Hash map","Binary heap","Queue"],1),q("BFS primarily uses which structure?",["Stack","Queue","Heap","Hash set"],1),q("O(n log n) describes what?",["A data type","Asymptotic growth","A network protocol","A transaction level"],1)]},
 {id:2,title:"Professional Programming",duration:"8 weeks",goal:"Write maintainable programs across the modern engineering toolchain.",topics:["Python","JavaScript","TypeScript","SQL","Bash"],projects:["CLI Password Manager","Compression Utility","Log Analyzer","Task Scheduler","Mini Shell"],questions:[q("What does TypeScript add to JavaScript?",["A database","Static type checking","A browser","A package manager"],1),q("Which principle reduces duplicated logic?",["DRY","FIFO","CAP","ACID"],0),q("A shell exit code of zero normally means?",["Failure","Success","Timeout","Permission denied"],1)]},
 {id:3,title:"Git & Team Development",duration:"2 weeks",goal:"Collaborate through reviewable, recoverable change.",topics:["Branching","Pull requests","Code review","Merge conflicts","Semantic versioning"],projects:["Five-person Simulated Team"],questions:[q("A pull request primarily enables?",["Code review","Database backup","Load balancing","Encryption"],0),q("Which version bump represents a breaking API change?",["Patch","Minor","Major","Build"],2),q("Rebase rewrites what?",["Working files only","Commit history","Remote permissions","Test coverage"],1)]},
 {id:4,title:"Databases",duration:"6 weeks",goal:"Store and retrieve data without sacrificing consistency.",topics:["PostgreSQL","Indexes","Transactions","Normalization","Query optimization","Redis"],projects:["Inventory System","School System","Bank Ledger","E-Commerce Database"],questions:[q("Which ACID property prevents partial transactions?",["Atomicity","Isolation","Durability","Consistency"],0),q("An index usually trades faster reads for?",["Less storage","Slower writes and storage","No constraints","Network latency"],1),q("Normalization primarily reduces?",["Encryption","Redundancy","Availability","Throughput"],1)]},
 {id:5,title:"Backend Engineering",duration:"8 weeks",goal:"Build secure, observable APIs with explicit contracts.",topics:["REST","Authentication","JWT","RBAC","Validation","Rate limiting","Caching"],projects:["Auth Service","Inventory API","Payment API","Multi-Tenant SaaS"],questions:[q("HTTP 401 means?",["Unauthenticated","Forbidden","Not found","Conflict"],0),q("RBAC grants access based on?",["Latency","Roles","IP only","Cache keys"],1),q("Input validation belongs at?",["Trust boundaries","CSS layer","DNS only","Build output"],0)]},
 {id:6,title:"Frontend Engineering",duration:"8 weeks",goal:"Build accessible, responsive and efficient interfaces.",topics:["React","State","Performance","Accessibility","Responsive design","Forms"],projects:["Kanban Board","Finance Dashboard","CRM","Inventory Dashboard"],questions:[q("A controlled React input stores its value in?",["DNS","State","CSS","A Docker layer"],1),q("Semantic HTML most directly improves?",["Accessibility","Database speed","Encryption","Caching"],0),q("Memoization is useful when?",["Work is expensive and inputs repeat","Every render must differ","Writing SQL","Routing packets"],0)]},
 {id:7,title:"Software Architecture",duration:"6 weeks",goal:"Choose boundaries and patterns based on tradeoffs.",topics:["Layered","Clean","Hexagonal","Event-driven","Microservices","CQRS","DDD"],projects:["Monolith Refactor","Modular Monolith","Microservices Comparison"],questions:[q("A modular monolith deploys as?",["One unit","A function per server","No process","Only containers"],0),q("Hexagonal architecture isolates domain logic from?",["Ports and adapters","Business rules","Tests","Types"],0),q("Microservices primarily add?",["Distributed-systems complexity","Automatic correctness","Zero latency","Free scaling"],0)]},
 {id:8,title:"Testing",duration:"4 weeks",goal:"Create confidence through layered automated verification.",topics:["Unit","Integration","End-to-end","Mocking","Contract testing","TDD"],projects:["95% Coverage Suite","CI Quality Gate"],questions:[q("A unit test should primarily isolate?",["A small behavior","The whole production network","Every browser","DNS"],0),q("Contract tests protect?",["Service interfaces","CSS colors","Disk space","Git history"],0),q("Coverage proves?",["Lines ran, not correctness","No bugs exist","Production readiness","Perfect design"],0)]},
 {id:9,title:"DevOps",duration:"8 weeks",goal:"Automate safe delivery and operations.",topics:["Linux","Docker","Kubernetes","CI/CD","GitHub Actions","Terraform","Monitoring"],projects:["Containerize Apps","Automated Deployments","Rollback Pipeline"],questions:[q("A container image should be?",["Immutable","Edited in production","A database","A secret store"],0),q("Infrastructure as code improves?",["Repeatability","Manual drift","Hidden changes","Password reuse"],0),q("A rollback restores?",["A known-good release","A deleted branch only","DNS ownership","Test mocks"],0)]},
 {id:10,title:"Cloud Engineering",duration:"6 weeks",goal:"Design secure, cost-aware cloud systems.",topics:["EC2","S3","Lambda","RDS","CloudFront","IAM"],projects:["Image Hosting","Video Backend","Serverless Analytics"],questions:[q("Least privilege applies to?",["IAM permissions","CSS","Sorting","Compression"],0),q("A CDN reduces?",["Content latency","Password entropy","Schema size","Git conflicts"],0),q("Object storage best fits?",["Images and blobs","Relational joins","CPU registers","Process locks"],0)]},
 {id:11,title:"Security Engineering",duration:"4 weeks",goal:"Build systems that fail safely under attack.",topics:["OWASP Top 10","Encryption","XSS","CSRF","SQL injection","Secrets"],projects:["Vulnerability Scanner","Secure Login","API Gateway"],questions:[q("Parameterized queries prevent?",["SQL injection","XSS","CSRF","DDoS"],0),q("Passwords should be stored using?",["A slow salted hash","Plain text","Reversible encoding","Git"],0),q("CSRF abuses?",["A user's authenticated browser","Database indexes","TLS certificates","Container layers"],0)]},
 {id:12,title:"System Design",duration:"8 weeks",goal:"Reason about scale, failure and tradeoffs.",topics:["Load balancing","Caching","Replication","Partitioning","Queues","CDNs","Streaming"],projects:["Netflix","WhatsApp","Uber","YouTube","Amazon","Banking","Tax Platform","National ID"],questions:[q("Horizontal scaling adds?",["More instances","More RAM to one host","A new language","A schema"],0),q("A queue primarily decouples?",["Producers and consumers","HTML and CSS","Rows and columns","Users and passwords"],0),q("Replication commonly improves?",["Read availability","Write simplicity","Strong consistency automatically","Zero cost"],0)]},
 {id:13,title:"AI Engineering",duration:"6 weeks",goal:"Build evaluated AI applications, not demos.",topics:["LLMs","Prompting","Embeddings","RAG","Agents","Vector databases","Evaluation"],projects:["Legal Assistant","Support Agent","Code Reviewer","Government Assistant"],questions:[q("RAG grounds a model with?",["Retrieved context","More CSS","A load balancer","JWT rotation"],0),q("Embeddings represent data as?",["Vectors","SQL locks","Containers","Certificates"],0),q("AI evaluation should use?",["Defined datasets and metrics","Vibes only","One prompt","No baselines"],0)]},
 {id:14,title:"Production Engineering",duration:"4 weeks",goal:"Operate systems through failure.",topics:["Incident response","Metrics","Observability","SLAs","SLOs","Error budgets"],projects:["Database Failure Drill","API Outage","Cache Corruption","Traffic Spike","Breach Simulation"],questions:[q("An SLO is?",["A reliability target","A legal contract","A log format","A database"],0),q("Observability helps infer?",["Internal state from outputs","Source ownership","CSS layout","Git identity"],0),q("A blameless postmortem optimizes for?",["Learning","Punishment","Secrecy","Speed alone"],0)]},
 {id:15,title:"Business Engineering",duration:"3 weeks",goal:"Translate business needs into viable systems.",topics:["Requirements","Stakeholders","Documentation","Cost","ROI"],projects:["Business Request to Delivery Plan"],questions:[q("A good requirement should be?",["Testable","Ambiguous","Implementation-only","Unowned"],0),q("ROI compares value with?",["Cost","Syntax","Latency only","Commit count"],0),q("Stakeholder discovery happens?",["Before and during delivery","Only after launch","Never","Only during incidents"],0)]}
];
export const capstones=["E-Commerce Platform","ERP System","Hospital Management Platform","Banking Core System","Fleet Management Platform","School Management Platform","Tax Collection Platform","Citizen Services Portal","AI Customer Support System","SaaS Subscription Platform"];
