import React from "react";
import {createRoot} from "react-dom/client";
import {Analytics} from "@vercel/analytics/react";
import {BrowserRouter,Link,NavLink,Route,Routes,useParams} from "react-router-dom";
import "./styles.css";

type Project={slug:string;title:string;type:string;status:string;description:string;stack:string[];problem:string;architecture:string;evidence:string[];failures:string[]};
const projects:Project[]=[
 {slug:"engineer-os",title:"EngineerOS",type:"Platform",status:"BUILDING",description:"The evidence-first developer operating system.",stack:["React","TypeScript","Vite"],problem:"Developer portfolios make claims but rarely expose proof.",architecture:"A routed React frontend today, designed to grow into a FastAPI and PostgreSQL modular monolith.",evidence:["Responsive public dashboard","Routed technical records","Vercel Analytics","Verified production build"],failures:["Technical record controls were initially inert.","The first README promised more than the application demonstrated."]},
 {slug:"inventory-system",title:"Inventory System",type:"Backend",status:"PLANNED",description:"Transactional stock control with an auditable movement ledger.",stack:["Python","FastAPI","PostgreSQL"],problem:"Stock updates become unreliable when systems overwrite totals without preserving movements.",architecture:"FastAPI modules, PostgreSQL transactions, append-only stock movements and a React operations UI.",evidence:["Domain boundaries identified","Core stack selected"],failures:["Implementation has not started; all metrics are targets."]},
 {slug:"route-optimization",title:"Route Optimization",type:"Algorithms",status:"PLANNED",description:"Shortest-path research applied to delivery routing.",stack:["Python","Graphs","A*"],problem:"Choose efficient routes across a weighted network under practical constraints.",architecture:"A benchmark harness comparing Dijkstra and A* with reproducible graph datasets.",evidence:["Algorithm candidates selected","Benchmark questions documented"],failures:["Real road-network constraints are not yet modeled."]},
 {slug:"school-platform",title:"School Platform",type:"Full stack",status:"PLANNED",description:"Students, classes, attendance and academic records.",stack:["React","FastAPI","PostgreSQL"],problem:"School records are fragmented and difficult to audit.",architecture:"A role-based React client over a FastAPI API and normalized PostgreSQL schema.",evidence:["Primary workflows mapped","Roles identified"],failures:["Permissions matrix remains incomplete."]}
];
const skills=[["Python",55],["React",70],["SQL",52],["DevOps",30],["System Design",22]] as const;
const designs=["Netflix","WhatsApp","Uber","YouTube","Banking System","Tax Platform"];
const capstones=["Amazon Lite","ERP","Hospital System","School Platform","Tax Collection System","Citizen Portal","AI Support Agent"];

function Layout(){return <div className="app"><header className="nav"><Link className="brand" to="/"><b>E</b>EngineerOS</Link><nav><NavLink to="/recruiter">Evidence</NavLink><NavLink to="/projects">Projects</NavLink><NavLink to="/dashboard">Journey</NavLink><NavLink to="/journal">Journal</NavLink></nav><a href="https://github.com/VictorMwatu-KE" target="_blank" rel="noreferrer">GitHub ↗</a></header><Routes><Route path="/" element={<Home/>}/><Route path="/recruiter" element={<Recruiter/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/projects" element={<Projects/>}/><Route path="/projects/:slug" element={<ProjectRecord/>}/><Route path="/system-design" element={<SystemDesign/>}/><Route path="/capstones" element={<Capstones/>}/><Route path="/interviews" element={<Interviews/>}/><Route path="/journal" element={<Journal/>}/><Route path="/admin" element={<Admin/>}/><Route path="*" element={<Page eyebrow="404" title="Record not found" text="This evidence does not exist yet."/>}/></Routes><footer>EngineerOS · Victor Huncho <span>Evidence over adjectives · 2026</span></footer></div>}

function Home(){return <><section className="hero shell"><small>● 12-MONTH ENGINEERING JOURNEY · IN PROGRESS</small><em>VICTOR MWATU · SOFTWARE ENGINEER</em><h1>Don’t trust the résumé.<br/><span>Inspect the evidence.</span></h1><p>A public operating system for everything I build, break, learn, deploy and document.</p><div className="actions"><Link className="primary" to="/recruiter">Open evidence dashboard</Link><Link className="secondary" to="/projects">Inspect projects</Link></div><div className="metrics">{[["0/25","Projects completed"],["0","Systems deployed"],["01/15","Current phase"],["0 days","Current streak"]].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></section><section className="shell section"><Heading eyebrow="CURRENT PHASE" title="Computer Science Fundamentals" text="Week 2 of 6 · Foundations before frameworks."/><Progress n={32}/></section><section className="shell section"><Heading eyebrow="EVIDENCE LAYERS" title="A portfolio built for inspection"/><div className="features">{[["Systems","Architecture, deployments, coverage and metrics.","/projects"],["Engineering trail","Decisions, incidents, failures and lessons.","/journal"],["Capability","Skills, Git activity and interview preparation.","/recruiter"],["Design thinking","Capacity, tradeoffs and scaling analysis.","/system-design"]].map((x,i)=><Link to={x[2]} key={x[0]}><small>0{i+1}</small><h3>{x[0]}</h3><p>{x[1]}</p><b>Inspect →</b></Link>)}</div></section></>}

function Recruiter(){return <Page eyebrow="PUBLIC ROUTE · /RECRUITER" title="Evidence dashboard" text="A transparent snapshot. Planned signals are never presented as shipped work."><div className="two"><Panel title="Skills matrix">{skills.map(([x,n])=><div className="skill" key={x}><span>{x}<b>{n}%</b></span><Progress n={n}/></div>)}</Panel><Panel title="GitHub activity"><Row x="Commits tracked" y="—"/><Row x="Pull requests" y="—"/><Row x="Public repositories" y="—"/><p className="note">Live GitHub data replaces placeholders when the integration ships.</p></Panel></div><h2 className="sub">Live systems</h2><div className="system"><b>● EngineerOS preview</b><span>PREVIEW</span><span>Response —</span><span>Uptime —</span></div><h2 className="sub">Public proof</h2><div className="proof">{[["1","Active build"],["0","Systems monitored"],["0","Incident reports"],["0","Certifications"]].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></Page>}

function Dashboard(){return <Page eyebrow="LEARNING DASHBOARD · MVP" title="Phase 1: Computer Science Fundamentals" text="Week 2 of 6 · 32% complete"><Panel title="Phase progress"><Progress n={32}/></Panel><div className="two"><Panel title="Topic tracker">{["Arrays","Linked lists","Stacks","Queues","Trees","Graphs"].map((x,i)=><label className="check" key={x}><input type="checkbox" defaultChecked={i<2}/>{x}</label>)}</Panel><Panel title="Journey map"><Row x="Current phase" y="01"/><Row x="Weeks logged" y="02"/><Row x="Projects shipped" y="00"/><Row x="Learning streak" y="0 days"/></Panel></div><div className="quick"><Link to="/system-design">System designs →</Link><Link to="/capstones">Capstones →</Link><Link to="/interviews">Interviews →</Link><Link to="/admin">Admin preview →</Link></div></Page>}

function Projects(){return <Page eyebrow="PROJECT VAULT" title="Systems, not screenshots" text="Each record separates implemented evidence from targets and plans."><div className="projects">{projects.map(p=><article key={p.slug}><header><span>{p.type}</span><b className={p.status==="BUILDING"?"live":""}>{p.status}</b></header><h2>{p.title}</h2><p>{p.description}</p><div className="stack">{p.stack.map(x=><span key={x}>{x}</span>)}</div><small>{p.status==="BUILDING"?"BUILD VERIFIED · PREVIEW LIVE":"TARGETS · NOT DEPLOYED"}</small><Link to={`/projects/${p.slug}`}>Open technical record →</Link></article>)}</div></Page>}
function ProjectRecord(){const p=projects.find(x=>x.slug===useParams().slug);if(!p)return <Page eyebrow="404" title="Record not found" text="No project matches this URL."/>;return <Page eyebrow={`TECHNICAL RECORD · ${p.type}`} title={p.title} text={p.description}><Link className="back" to="/projects">← All projects</Link><div className="record"><main><Section n="01" title="Problem"><p>{p.problem}</p></Section><Section n="02" title="Architecture"><p>{p.architecture}</p><div className="diagram"><span>React</span>→<span>FastAPI</span>→<span>PostgreSQL</span></div></Section><Section n="03" title="Evidence"><ul>{p.evidence.map(x=><li key={x}>{x}</li>)}</ul></Section><Section n="04" title="Failures & lessons"><ul>{p.failures.map(x=><li key={x}>{x}</li>)}</ul></Section></main><aside><b className={p.status==="BUILDING"?"live":""}>{p.status}</b><Row x="Deployment" y={p.status==="BUILDING"?"Preview":"None"}/><Row x="Coverage" y={p.status==="BUILDING"?"Build verified":"Target"}/><div className="stack">{p.stack.map(x=><span key={x}>{x}</span>)}</div></aside></div></Page>}

function SystemDesign(){return <Page eyebrow="SYSTEM DESIGN" title="Architecture under pressure" text="Capacity, constraints, tradeoffs and failure modes."><div className="designs">{designs.map((x,i)=><article key={x}><small>CASE STUDY 0{i+1}</small><h2>{x}</h2><p>Architecture · scaling · capacity · tradeoffs</p><b>PLANNED</b></article>)}</div></Page>}
function Capstones(){return <Page eyebrow="CAPSTONE TRACKER" title="Seven systems. Full lifecycle." text="Architecture, implementation, tests, deployment and documentation."><div className="list">{capstones.map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><Progress n={i===3?8:0}/><small>{i===3?"DISCOVERY":"QUEUED"}</small></div>)}</div></Page>}
function Interviews(){return <Page eyebrow="INTERVIEW TRACKER" title="Preparation without vanity metrics" text="Numbers update only when evidence is logged."><div className="proof">{[["0","LeetCode solved"],["0","Mock interviews"],["0","System designs"],["0","Debugging challenges"]].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div><Panel title="Preparation lanes"><Row x="Algorithms" y="STARTED"/><Row x="System design" y="PLANNED"/><Row x="Behavioral stories" y="PLANNED"/><Row x="Debugging drills" y="PLANNED"/></Panel></Page>}
function Journal(){return <Page eyebrow="ENGINEERING JOURNAL" title="The work behind the work" text="Decisions, bugs, incidents and lessons—not polished hindsight."><article className="journal"><small>DAY 001 · BUILD LOG</small><h2>Turned project labels into inspectable records.</h2><dl><dt>Problem</dt><dd>Technical record controls looked interactive but did nothing.</dd><dt>Root cause</dt><dd>The MVP only changed state for top-level navigation.</dd><dt>Solution</dt><dd>Added routed, data-driven records with evidence and failure sections.</dd><dt>Lesson</dt><dd>An interface promise is still a promise.</dd></dl></article></Page>}
function Admin(){return <Page eyebrow="PRIVATE ROUTE · PREVIEW" title="Control room" text="Authentication and persistence are required before these controls become operational."><div className="admin">{["Update progress","Add project evidence","Publish journal","Upload diagram","Add certification","Record deployment"].map(x=><button disabled key={x}>{x}<small>BACKEND REQUIRED</small></button>)}</div></Page>}

function Page({eyebrow,title,text,children}:{eyebrow:string;title:string;text:string;children?:React.ReactNode}){return <section className="shell page"><Heading eyebrow={eyebrow} title={title} text={text}/>{children}</section>}
function Heading({eyebrow,title,text}:{eyebrow:string;title:string;text?:string}){return <header className="heading"><small>{eyebrow}</small><h1>{title}</h1>{text&&<p>{text}</p>}</header>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><h2>{title}</h2>{children}</section>}
function Progress({n}:{n:number}){return <div className="progress"><span style={{width:`${n}%`}}/></div>}
function Row({x,y}:{x:string;y:string}){return <div className="row"><span>{x}</span><b>{y}</b></div>}
function Section({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <section className="record-section"><small>{n}</small><div><h2>{title}</h2>{children}</div></section>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><BrowserRouter><Layout/><Analytics/></BrowserRouter></React.StrictMode>);
